export default {
  main: 'h-[100vh] overflow-hidden rounded-lg backdrop-blur-lg',
  chartBgFill: '#333',
  'intel-main-color': '#007cc1',
  'amd-main-color': '#ed1f23',
  'nvidia-main-color': '#71b000',
  'temperature-color': '#e879f9',
  'power-color': '#06b6d4',
  'voltage-color': '#f59e0b',
  // 'bullet-bg-color-1': '#a3ff6e',
  // 'bullet-bg-color-2': '#ffad32',
  // 'bullet-bg-color-3': '#ff5c5c',
  // 'bullet-bg-color-4': '#f72d2d',
  'bullet-bg-color-1': '#fff',
  'bullet-bg-color-2': 'transparent',
  'bullet-bg-color-3': '#fff',
  // 'bullet-bg-color-4': '#888',
  'percentage-color-1': '#51ff4e',
  'percentage-color-2': '#96ff22',
  'percentage-color-3': '#d4ff29',
  'percentage-color-4': '#ecef24',
  'percentage-color-5': '#efcd24',
  'percentage-color-6': '#ffad32',
  'percentage-color-7': '#ef7722',
  'percentage-color-8': '#ff5c5c',
  'percentage-color-9': '#e93b3b',
  'percentage-color-10': '#f72d2d'
};
